# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstagramApp', '0008_sendsms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendSMS',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='number',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
