# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstagramApp', '0009_auto_20170915_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='number',
            field=models.IntegerField(),
        ),
    ]
