# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstagramApp', '0015_auto_20170916_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
